<?php

namespace Database\Seeders;

use App\Models\Region;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RegionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $data = [
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' => 'CIBINONG'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' => 'GUNUNG PUTRI'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'CITEUREUP'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'SUKARAJA'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'BABAKAN MADANG'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'JONGGOL'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'CILEUNGSI'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'CARIU'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'SUKAMAKMUR'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'PARUNG'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'GUNUNG SINDUR'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'KEMANG'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'BOJONG GEDE'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'LEUWILIANG'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'CIAMPEA'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'CIBUNGBULANG'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'PAMIJAHAN'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'RUMPIN'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'JASINGA'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'PARUNG PANJANG'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'NANGGUNG'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'CIGUDEG'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'TENJO'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'CIAWI'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'CISARUA'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'MEGAMENDUNG'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'CARINGIN'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'CIJERUK'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'CIOMAS'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'DRAMAGA'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'TAMANSARI'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'KLAPANUNGGAL'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'CISEENG'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'RANCA BUNGUR'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'SUKAJAYA'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'TANJUNGSARI'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'TAJURHALANG'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'CIGOMBONG'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'LEUWISADENG'],
            ['dkc_name' => 'KABUPATEN BOGOR', 'dkr_name' =>    'TENJOLAYA'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'PALABUHANRATU'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'SIMPENAN'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'CIKAKAK'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'BANTARGADUNG'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'CISOLOK'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'CIKIDANG'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'LENGKONG'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'JAMPANGTENGAH'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'WARUNGKIARA'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'CIKEMBAR'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'CIBADAK'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'NAGRAK'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'PARUNGKUDA'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'BOJONGGENTENG'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'PARAKANSALAK'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'CICURUG'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'CIDAHU'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'KALAPANUNGGAL'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'KABANDUNGAN'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'WALURAN'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'JAMPANGKULON'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'CIEMAS'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'KALIBUNDER'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'SURADE'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'CIBITUNG'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'CIRACAP'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'GUNUNGGURUH'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'CICANTAYAN'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'CISAAT'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'KADUDAMPIT'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'CARINGIN'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'SUKABUMI'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'SUKARAJA'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'KEBONPEDES'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'CIREUNGHAS'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'SUKALARANG'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'PABUARAN'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'PURABAYA'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'NYALINDUNG'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'GEGERBITUNG'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'SAGARANTEN'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'CURUGKEMBAR'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'CIDOLOG'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'CIDADAP'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'TEGALBULEUD'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'CIMANGGU'],
            ['dkc_name' => 'KABUPATEN SUKABUMI', 'dkr_name' =>    'CIAMBAR'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'CIANJUR'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'WARUNGKONDANG'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'CIBEBER'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'CILAKU'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'CIRANJANG'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'BOJONGPICUNG'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'KARANGTENGAH'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'MANDE'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'SUKALUYU'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'PACET'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'CUGENANG'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'CIKALONGKULON'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'SUKARESMI'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'SUKANAGARA'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'CAMPAKA'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'TAKOKAK'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'KADUPANDAK'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'PAGELARAN'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'TANGGEUNG'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'CIBINONG'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'SINDANGBARANG'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'AGRABINTA'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'CIDAUN'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'NARINGGUL'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'CAMPAKAMULYA'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'CIKADU'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'GEKBRONG'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'CIPANAS'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'CIJATI'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'LELES'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'HAURWANGI'],
            ['dkc_name' => 'KABUPATEN CIANJUR', 'dkr_name' =>    'PASIRKUDA'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'CILEUNYI'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'CIMENYAN'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'CILENGKRANG'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'BOJONGSOANG'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'MARGAHAYU'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'MARGAASIH'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'KATAPANG'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'DAYEUHKOLOT'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'BANJARAN'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'PAMEUNGPEUK'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'PANGALENGAN'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'ARJASARI'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'CIMAUNG'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'CICALENGKA'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'NAGREG'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'CIKANCUNG'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'RANCAEKEK'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'CIPARAY'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'PACET'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'KERTASARI'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'BALEENDAH'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'MAJALAYA'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'SOLOKANJERUK'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'PASEH'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'IBUN'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'SOREANG'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'PASIRJAMBU'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'CIWIDEY'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'RANCABALI'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'CANGKUANG'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' =>    'KUTAWARINGIN'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'GARUT KOTA'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'KARANGPAWITAN'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'WANARAJA'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'TAROGONG KALER'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'TAROGONG KIDUL'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'BANYURESMI'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'SAMARANG'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'PASIRWANGI'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'LELES'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'KADUNGORA'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'LEUWIGOONG'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'CIBATU'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'KERSAMANAH'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'MALANGBONG'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'SUKAWENING'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'KARANGTENGAH'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'BAYONGBONG'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'CIGEDUG'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'CILAWU'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'CISURUPAN'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'SUKARESMI'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'CIKAJANG'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'BANJARWANGI'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'SINGAJAYA'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'CIHURIP'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'PEUNDEUY'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'PAMEUNGPEUK'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'CISOMPET'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'CIBALONG'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'CIKELET'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'BUNGBULANG'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'MEKARMUKTI'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'PAKENJENG'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'PAMULIHAN'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'CISEWU'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'CARINGIN'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'TALEGONG'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'LIMBANGAN'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'SELAAWI'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'CIBIUK'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'PANGATIKAN'],
            ['dkc_name' => 'KABUPATEN GARUT', 'dkr_name' =>    'SUCINARAJA'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'CIPATUJAH'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'KARANGNUNGGAL'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'CIKALONG'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'PANCATENGAH'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'CIKATOMAS'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'CIBALONG'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'PARUNGPONTENG'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'BANTARKALONG'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'BOJONGASIH'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'CULAMEGA'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'BOJONGGAMBIR'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'SODONGHILIR'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'TARAJU'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'SALAWU'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'PUSPAHIANG'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'TANJUNGJAYA'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'SUKARAJA'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'SALOPA'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'JATIWARAS'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'CINEAM'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'KARANG JAYA'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'MANONJAYA'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'GUNUNG TANJUNG'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'SINGAPARNA'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'MANGUNREJA'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'SUKARAME'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'CIGALONTANG'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'LEUWISARI'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'PADAKEMBANG'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'SARIWANGI'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'SUKARATU'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'CISAYONG'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'SUKAHENING'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'RAJAPOLAH'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'JAMANIS'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'CIAWI'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'KADIPATEN'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'PAGERAGEUNG'],
            ['dkc_name' => 'KABUPATEN TASIKMALAYA', 'dkr_name' =>    'SUKARESIK'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'CIAMIS'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'CIKONENG'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'CIJEUNGJING'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'SADANANYA'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'CIDOLOG'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'CIHAURBEUTI'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'PANUMBANGAN'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'PANJALU'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'KAWALI'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'PANAWANGAN'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'CIPAKU'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'JATINAGARA'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'RAJADESA'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'SUKADANA'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'RANCAH'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'TAMBAKSARI'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'LAKBOK'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'BANJARSARI'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'PAMARICAN'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'CIMARAGAS'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'CISAGA'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'SINDANGKASIH'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'BAREGBEG'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'SUKAMANTRI'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'LUMBUNG'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'PURWADADI'],
            ['dkc_name' => 'KABUPATEN CIAMIS', 'dkr_name' =>    'BANJARANYAR'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'KADUGEDE'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'CINIRU'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'SUBANG'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'CIWARU'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'CIBINGBIN'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'LURAGUNG'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'LEBAKWANGI'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'GARAWANGI'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'KUNINGAN'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'CIAWIGEBANG'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'CIDAHU'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'JALAKSANA'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'CILIMUS'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'MANDIRANCAN'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'SELAJAMBE'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'KRAMATMULYA'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'DARMA'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'CIGUGUR'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'PASAWAHAN'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'NUSAHERANG'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'CIPICUNG'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'PANCALANG'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'JAPARA'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'CIMAHI'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'CILEBAK'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'HANTARA'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'KALIMANGGIS'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'CIBEUREUM'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'KARANG KANCANA'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'MALEBER'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'SINDANG AGUNG'],
            ['dkc_name' => 'KABUPATEN KUNINGAN', 'dkr_name' =>    'CIGANDAMEKAR'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'WALED'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'CILEDUG'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'LOSARI'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'PABEDILAN'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'BABAKAN'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'KARANGSEMBUNG'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'LEMAHABANG'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'SUSUKAN LEBAK'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'SEDONG'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'ASTANAJAPURA'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'PANGENAN'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'MUNDU'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'BEBER'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'TALUN'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'SUMBER'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'DUKUPUNTANG'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'PALIMANAN'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'PLUMBON'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'WERU'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'KEDAWUNG'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'GUNUNG JATI'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'KAPETAKAN'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'KLANGENAN'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'ARJAWINANGUN'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'PANGURAGAN'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'CIWARINGIN'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'SUSUKAN'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'GEGESIK'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'KALIWEDI'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'GEBANG'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'DEPOK'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'PASALEMAN'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'PABUARAN'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'KARANGWARENG'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'TENGAH TANI'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'PLERED'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'GEMPOL'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'GREGED'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'SURANENGGALA'],
            ['dkc_name' => 'KABUPATEN CIREBON', 'dkr_name' =>    'JAMBLANG'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'LEMAHSUGIH'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'BANTARUJEG'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'CIKIJING'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'TALAGA'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'ARGAPURA'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'MAJA'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'MAJALENGKA'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'SUKAHAJI'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'RAJAGALUH'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'LEUWIMUNDING'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'JATIWANGI'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'DAWUAN'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'KADIPATEN'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'KERTAJATI'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'JATITUJUH'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'LIGUNG'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'SUMBERJAYA'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'PANYINGKIRAN'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'PALASAH'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'CIGASONG'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'SINDANGWANGI'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'BANJARAN'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'CINGAMBUL'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'KASOKANDEL'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'SINDANG'],
            ['dkc_name' => 'KABUPATEN MAJALENGKA', 'dkr_name' =>    'MALAUSMA'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'WADO'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'JATINUNGGAL'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'DARMARAJA'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'CIBUGEL'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'CISITU'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'SITURAJA'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'CONGGEANG'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'PASEH'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'SURIAN'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'BUAHDUA'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'TANJUNGSARI'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'SUKASARI'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'PAMULIHAN'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'CIMANGGUNG'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'JATINANGOR'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'RANCAKALONG'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'SUMEDANG SELATAN'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'SUMEDANG UTARA'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'GANEAS'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'TANJUNGKERTA'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'TANJUNGMEDAR'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'CIMALAKA'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'CISARUA'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'TOMO'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'UJUNGJAYA'],
            ['dkc_name' => 'KABUPATEN SUMEDANG', 'dkr_name' =>    'JATIGEDE'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'HAURGEULIS'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'KROYA'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'GABUSWETAN'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'CIKEDUNG'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'LELEA'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'BANGODUA'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'WIDASARI'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'KERTASEMAYA'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'KRANGKENG'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'KARANGAMPEL'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'JUNTINYUAT'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'SLIYEG'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'JATIBARANG'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'BALONGAN'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'INDRAMAYU'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'SINDANG'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'CANTIGI'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'LOHBENER'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'ARAHAN'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'LOSARANG'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'KANDANGHAUR'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'BONGAS'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'ANJATAN'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'SUKRA'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'GANTAR'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'TRISI'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'SUKAGUMIWANG'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'KEDOKAN BUNDER'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'PASEKAN'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'TUKDANA'],
            ['dkc_name' => 'KABUPATEN INDRAMAYU', 'dkr_name' =>    'PATROL'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'SAGALAHERANG'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'CISALAK'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'SUBANG'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'KALIJATI'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'PABUARAN'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'PURWADADI'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'PAGADEN'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'BINONG'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'CIASEM'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'PUSAKANAGARA'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'PAMANUKAN'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'JALANCAGAK'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'BLANAKAN'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'TANJUNGSIANG'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'COMPRENG'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'PATOKBEUSI'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'CIBOGO'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'CIPUNAGARA'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'CIJAMBE'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'CIPEUNDEUY'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'LEGONKULON'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'CIKAUM'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'SERANGPANJANG'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'SUKASARI'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'TAMBAKDAHAN'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'KASOMALANG'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'DAWUAN'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'PAGADEN BARAT'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'CIATER'],
            ['dkc_name' => 'KABUPATEN SUBANG', 'dkr_name' =>    'PUSAKAJAYA'],
            ['dkc_name' => 'KABUPATEN PURWAKARTA', 'dkr_name' =>    'PURWAKARTA'],
            ['dkc_name' => 'KABUPATEN PURWAKARTA', 'dkr_name' =>    'CAMPAKA'],
            ['dkc_name' => 'KABUPATEN PURWAKARTA', 'dkr_name' =>    'JATILUHUR'],
            ['dkc_name' => 'KABUPATEN PURWAKARTA', 'dkr_name' =>    'PLERED'],
            ['dkc_name' => 'KABUPATEN PURWAKARTA', 'dkr_name' =>    'SUKATANI'],
            ['dkc_name' => 'KABUPATEN PURWAKARTA', 'dkr_name' =>    'DARANGDAN'],
            ['dkc_name' => 'KABUPATEN PURWAKARTA', 'dkr_name' =>    'MANIIS'],
            ['dkc_name' => 'KABUPATEN PURWAKARTA', 'dkr_name' =>    'TEGALWARU'],
            ['dkc_name' => 'KABUPATEN PURWAKARTA', 'dkr_name' =>    'WANAYASA'],
            ['dkc_name' => 'KABUPATEN PURWAKARTA', 'dkr_name' =>    'PASAWAHAN'],
            ['dkc_name' => 'KABUPATEN PURWAKARTA', 'dkr_name' =>    'BOJONG'],
            ['dkc_name' => 'KABUPATEN PURWAKARTA', 'dkr_name' =>    'BABAKANCIKAO'],
            ['dkc_name' => 'KABUPATEN PURWAKARTA', 'dkr_name' =>    'BUNGURSARI'],
            ['dkc_name' => 'KABUPATEN PURWAKARTA', 'dkr_name' =>    'CIBATU'],
            ['dkc_name' => 'KABUPATEN PURWAKARTA', 'dkr_name' =>    'SUKASARI'],
            ['dkc_name' => 'KABUPATEN PURWAKARTA', 'dkr_name' =>    'PONDOKSALAM'],
            ['dkc_name' => 'KABUPATEN PURWAKARTA', 'dkr_name' =>    'KIARAPEDES'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'KARAWANG BARAT'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'PANGKALAN'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'TELUKJAMBE TIMUR'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'CIAMPEL'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'KLARI'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'RENGASDENGKLOK'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'KUTAWALUYA'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'BATUJAYA'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'TIRTAJAYA'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'PEDES'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'CIBUAYA'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'PAKISJAYA'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'CIKAMPEK'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'JATISARI'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'CILAMAYA WETAN'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'TIRTAMULYA'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'TELAGASARI'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'RAWAMERTA'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'LEMAHABANG'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'TEMPURAN'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'MAJALAYA'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'JAYAKERTA'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'CILAMAYA KULON'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'BANYUSARI'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'KOTA BARU'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'KARAWANG TIMUR'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'TELUKJAMBE BARAT'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'TEGALWARU'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'PURWASARI'],
            ['dkc_name' => 'KABUPATEN KARAWANG', 'dkr_name' =>    'CILEBAR'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'TARUMAJAYA'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'BABELAN'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'SUKAWANGI'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'TAMBELANG'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'TAMBUN UTARA'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'TAMBUN SELATAN'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'CIBITUNG'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'CIKARANG BARAT'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'CIKARANG UTARA'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'KARANG BAHAGIA'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'CIKARANG TIMUR'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'KEDUNG WARINGIN'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'PEBAYURAN'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'SUKAKARYA'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'SUKATANI'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'CABANGBUNGIN'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'MUARAGEMBONG'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'SETU'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'CIKARANG SELATAN'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'CIKARANG PUSAT'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'SERANG BARU'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'CIBARUSAH'],
            ['dkc_name' => 'KABUPATEN BEKASI', 'dkr_name' =>    'BOJONGMANGU'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' => 'BARAT	LEMBANG'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' => 'BARAT	PARONGPONG'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' => 'BARAT	CISARUA'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' => 'BARAT	CIKALONGWETAN'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' => 'BARAT	CIPEUNDEUY'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' => 'BARAT	NGAMPRAH'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' => 'BARAT	CIPATAT'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' => 'BARAT	PADALARANG'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' => 'BARAT	BATUJAJAR'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' => 'BARAT	CIHAMPELAS'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' => 'BARAT	CILILIN'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' => 'BARAT	CIPONGKOR'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' => 'BARAT	RONGGA'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' => 'BARAT	SINDANGKERTA'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' => 'BARAT	GUNUNGHALU'],
            ['dkc_name' => 'KABUPATEN BANDUNG', 'dkr_name' => 'BARAT	SAGULING'],
            ['dkc_name' => 'KABUPATEN PANGANDARAN', 'dkr_name' =>    'PARIGI'],
            ['dkc_name' => 'KABUPATEN PANGANDARAN', 'dkr_name' =>    'CIJULANG'],
            ['dkc_name' => 'KABUPATEN PANGANDARAN', 'dkr_name' =>    'CIMERAK'],
            ['dkc_name' => 'KABUPATEN PANGANDARAN', 'dkr_name' =>    'CIGUGUR'],
            ['dkc_name' => 'KABUPATEN PANGANDARAN', 'dkr_name' =>    'LANGKAPLANCAR'],
            ['dkc_name' => 'KABUPATEN PANGANDARAN', 'dkr_name' =>    'MANGUNJAYA'],
            ['dkc_name' => 'KABUPATEN PANGANDARAN', 'dkr_name' =>    'PADAHERANG'],
            ['dkc_name' => 'KABUPATEN PANGANDARAN', 'dkr_name' =>    'KALIPUCANG'],
            ['dkc_name' => 'KABUPATEN PANGANDARAN', 'dkr_name' =>    'PANGANDARAN'],
            ['dkc_name' => 'KABUPATEN PANGANDARAN', 'dkr_name' =>    'SIDAMULIH'],
            ['dkc_name' => 'KOTA BOGOR', 'dkr_name' =>    'BOGOR SELATAN'],
            ['dkc_name' => 'KOTA BOGOR', 'dkr_name' =>    'BOGOR TIMUR'],
            ['dkc_name' => 'KOTA BOGOR', 'dkr_name' =>    'BOGOR TENGAH'],
            ['dkc_name' => 'KOTA BOGOR', 'dkr_name' =>    'BOGOR BARAT'],
            ['dkc_name' => 'KOTA BOGOR', 'dkr_name' =>    'BOGOR UTARA'],
            ['dkc_name' => 'KOTA BOGOR', 'dkr_name' =>    'TANAH SAREAL'],
            ['dkc_name' => 'KOTA SUKABUMI', 'dkr_name' =>    'GUNUNGPUYUH'],
            ['dkc_name' => 'KOTA SUKABUMI', 'dkr_name' =>    'CIKOLE'],
            ['dkc_name' => 'KOTA SUKABUMI', 'dkr_name' =>    'CITAMIANG'],
            ['dkc_name' => 'KOTA SUKABUMI', 'dkr_name' =>    'WARUDOYONG'],
            ['dkc_name' => 'KOTA SUKABUMI', 'dkr_name' =>    'BAROS'],
            ['dkc_name' => 'KOTA SUKABUMI', 'dkr_name' =>    'LEMBURSITU'],
            ['dkc_name' => 'KOTA SUKABUMI', 'dkr_name' =>    'CIBEUREUM'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'SUKASARI'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'COBLONG'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'BABAKAN CIPARAY'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'BOJONGLOA KALER'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'ANDIR'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'CICENDO'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'SUKAJADI'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'CIDADAP'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'BANDUNG WETAN'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'ASTANA ANYAR'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'REGOL'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'BATUNUNGGAL'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'LENGKONG'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'CIBEUNYING KIDUL'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'BANDUNG KULON'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'KIARACONDONG'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'BOJONGLOA KIDUL'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'CIBEUNYING KALER'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'SUMUR BANDUNG'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'ANTAPANI'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'BANDUNG KIDUL'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'BUAHBATU'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'RANCASARI'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'ARCAMANIK'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'CIBIRU'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'UJUNGBERUNG'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'GEDEBAGE'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'PANYILEUKAN'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'CINAMBO'],
            ['dkc_name' => 'KOTA BANDUNG', 'dkr_name' =>    'MANDALAJATI'],
            ['dkc_name' => 'KOTA CIREBON', 'dkr_name' =>    'KEJAKSAN'],
            ['dkc_name' => 'KOTA CIREBON', 'dkr_name' =>    'LEMAH WUNGKUK'],
            ['dkc_name' => 'KOTA CIREBON', 'dkr_name' =>    'HARJAMUKTI'],
            ['dkc_name' => 'KOTA CIREBON', 'dkr_name' =>    'PEKALIPAN'],
            ['dkc_name' => 'KOTA CIREBON', 'dkr_name' =>    'KESAMBI'],
            ['dkc_name' => 'KOTA BEKASI', 'dkr_name' =>    'BEKASI TIMUR'],
            ['dkc_name' => 'KOTA BEKASI', 'dkr_name' =>    'BEKASI BARAT'],
            ['dkc_name' => 'KOTA BEKASI', 'dkr_name' =>    'BEKASI UTARA'],
            ['dkc_name' => 'KOTA BEKASI', 'dkr_name' =>    'BEKASI SELATAN'],
            ['dkc_name' => 'KOTA BEKASI', 'dkr_name' =>    'RAWALUMBU'],
            ['dkc_name' => 'KOTA BEKASI', 'dkr_name' =>    'MEDANSATRIA'],
            ['dkc_name' => 'KOTA BEKASI', 'dkr_name' =>    'BANTARGEBANG'],
            ['dkc_name' => 'KOTA BEKASI', 'dkr_name' =>    'PONDOKGEDE'],
            ['dkc_name' => 'KOTA BEKASI', 'dkr_name' =>    'JATIASIH'],
            ['dkc_name' => 'KOTA BEKASI', 'dkr_name' =>    'JATISAMPURNA'],
            ['dkc_name' => 'KOTA BEKASI', 'dkr_name' =>    'MUSTIKAJAYA'],
            ['dkc_name' => 'KOTA BEKASI', 'dkr_name' =>    'PONDOKMELATI'],
            ['dkc_name' => 'KOTA DEPOK', 'dkr_name' =>    'PANCORAN MAS'],
            ['dkc_name' => 'KOTA DEPOK', 'dkr_name' =>    'CIMANGGIS'],
            ['dkc_name' => 'KOTA DEPOK', 'dkr_name' =>    'SAWANGAN'],
            ['dkc_name' => 'KOTA DEPOK', 'dkr_name' =>    'LIMO'],
            ['dkc_name' => 'KOTA DEPOK', 'dkr_name' =>    'SUKMAJAYA'],
            ['dkc_name' => 'KOTA DEPOK', 'dkr_name' =>    'BEJI'],
            ['dkc_name' => 'KOTA DEPOK', 'dkr_name' =>    'CIPAYUNG'],
            ['dkc_name' => 'KOTA DEPOK', 'dkr_name' =>    'CILODONG'],
            ['dkc_name' => 'KOTA DEPOK', 'dkr_name' =>    'CINERE'],
            ['dkc_name' => 'KOTA DEPOK', 'dkr_name' =>    'TAPOS'],
            ['dkc_name' => 'KOTA DEPOK', 'dkr_name' =>    'BOJONGSARI'],
            ['dkc_name' => 'KOTA CIMAHI', 'dkr_name' =>    'CIMAHI SELATAN'],
            ['dkc_name' => 'KOTA CIMAHI', 'dkr_name' =>    'CIMAHI TENGAH'],
            ['dkc_name' => 'KOTA CIMAHI', 'dkr_name' =>    'CIMAHI UTARA'],
            ['dkc_name' => 'KOTA TASIKMALAYA', 'dkr_name' =>    'CIHIDEUNG'],
            ['dkc_name' => 'KOTA TASIKMALAYA', 'dkr_name' =>    'CIPEDES'],
            ['dkc_name' => 'KOTA TASIKMALAYA', 'dkr_name' =>    'TAWANG'],
            ['dkc_name' => 'KOTA TASIKMALAYA', 'dkr_name' =>    'INDIHIANG'],
            ['dkc_name' => 'KOTA TASIKMALAYA', 'dkr_name' =>    'KAWALU'],
            ['dkc_name' => 'KOTA TASIKMALAYA', 'dkr_name' =>    'CIBEUREUM'],
            ['dkc_name' => 'KOTA TASIKMALAYA', 'dkr_name' =>    'TAMANSARI'],
            ['dkc_name' => 'KOTA TASIKMALAYA', 'dkr_name' =>    'MANGKUBUMI'],
            ['dkc_name' => 'KOTA TASIKMALAYA', 'dkr_name' =>    'BUNGURSARI'],
            ['dkc_name' => 'KOTA TASIKMALAYA', 'dkr_name' =>    'PURBARATU'],
            ['dkc_name' => 'KOTA BANJAR', 'dkr_name' =>    'BANJAR'],
            ['dkc_name' => 'KOTA BANJAR', 'dkr_name' =>    'PATARUMAN'],
            ['dkc_name' => 'KOTA BANJAR', 'dkr_name' =>    'PURWAHARJA'],
            ['dkc_name' => 'KOTA BANJAR', 'dkr_name' =>    'LANGENSARI'],

        ];

        foreach ($data as $key => $value) {
            Region::create($value);
        }
    }
}
