<?php

namespace Database\Seeders;

use App\Models\Regency;
use App\Models\Region;
use App\Models\Villages;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RegionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $dataRegency = [
            ['name'    => 'KABUPATEN BOGOR'],
            ['name'    => 'KABUPATEN SUKABUMI'],
            ['name'    => 'KABUPATEN CIANJUR'],
            ['name'    => 'KABUPATEN BANDUNG'],
            ['name'    => 'KABUPATEN GARUT'],
            ['name'    => 'KABUPATEN TASIKMALAYA'],
            ['name'    => 'KABUPATEN CIAMIS'],
            ['name'    => 'KABUPATEN KUNINGAN'],
            ['name'    => 'KABUPATEN CIREBON'],
            ['name'   => 'KABUPATEN MAJALENGKA'],
            ['name'   => 'KABUPATEN SUMEDANG'],
            ['name'   => 'KABUPATEN INDRAMAYU'],
            ['name'   => 'KABUPATEN SUBANG'],
            ['name'   => 'KABUPATEN PURWAKARTA'],
            ['name'   => 'KABUPATEN KARAWANG'],
            ['name'   => 'KABUPATEN BEKASI'],
            ['name'   => 'KABUPATEN BANDUNG BARAT'],
            ['name'   => 'KABUPATEN PANGANDARAN'],
            ['name'   => 'KOTA BOGOR'],
            ['name'   => 'KOTA SUKABUMI'],
            ['name'   => 'KOTA BANDUNG'],
            ['name'   => 'KOTA CIREBON'],
            ['name'   => 'KOTA BEKASI'],
            ['name'   => 'KOTA DEPOK'],
            ['name'   => 'KOTA CIMAHI'],
            ['name'   => 'KOTA TASIKMALAYA'],
            ['name'   => 'KOTA BANJAR'],
        ];

        foreach ($dataRegency as $key => $value) {
            Regency::create($value);
        }

        $kabbogor           = Regency::where('name', 'KABUPATEN BOGOR')->first();
        $kabsukabumi        = Regency::where('name', 'KABUPATEN SUKABUMI')->first();
        $kabcianjur         = Regency::where('name', 'KABUPATEN CIANJUR')->first();
        $kabbandung         = Regency::where('name', 'KABUPATEN BANDUNG')->first();
        $kabgarut           = Regency::where('name', 'KABUPATEN GARUT')->first();
        $kabtasikmalaya     = Regency::where('name', 'KABUPATEN TASIKMALAYA')->first();
        $kabciamis          = Regency::where('name', 'KABUPATEN CIAMIS')->first();
        $kabkuningan        = Regency::where('name', 'KABUPATEN KUNINGAN')->first();
        $kabcirebon         = Regency::where('name', 'KABUPATEN CIREBON')->first();
        $kabmajalengka      = Regency::where('name', 'KABUPATEN MAJALENGKA')->first();
        $kabsumedang        = Regency::where('name', 'KABUPATEN SUMEDANG')->first();
        $kabindramayu       = Regency::where('name', 'KABUPATEN INDRAMAYU')->first();
        $kabsubang          = Regency::where('name', 'KABUPATEN SUBANG')->first();
        $kabpurwakarta      = Regency::where('name', 'KABUPATEN PURWAKARTA')->first();
        $kabkarawang        = Regency::where('name', 'KABUPATEN KARAWANG')->first();
        $kabbekasi          = Regency::where('name', 'KABUPATEN BEKASI')->first();
        $kabbandungbarat    = Regency::where('name', 'KABUPATEN BANDUNG BARAT')->first();
        $kabpangandaran     = Regency::where('name', 'KABUPATEN PANGANDARAN')->first();
        $kotabogor          = Regency::where('name', 'KOTA BOGOR')->first();
        $kotasukabumi       = Regency::where('name', 'KOTA SUKABUMI')->first();
        $kotabandung        = Regency::where('name', 'KOTA BANDUNG')->first();
        $kotacirebon        = Regency::where('name', 'KOTA CIREBON')->first();
        $kotabekasi         = Regency::where('name', 'KOTA BEKASI')->first();
        $kotadepok          = Regency::where('name', 'KOTA DEPOK')->first();
        $kotacimahi         = Regency::where('name', 'KOTA CIMAHI')->first();
        $kotatasikmalaya    = Regency::where('name', 'KOTA TASIKMALAYA')->first();
        $kotabanjar         = Regency::where('name', 'KOTA BANJAR')->first();

        $dataVillages = [
            ['regency_id' => $kabbogor->id, 'name' => 'CIBINONG'],
            ['regency_id' => $kabbogor->id, 'name' => 'GUNUNG PUTRI'],
            ['regency_id' => $kabbogor->id, 'name' => 'CITEUREUP'],
            ['regency_id' => $kabbogor->id, 'name' => 'SUKARAJA'],
            ['regency_id' => $kabbogor->id, 'name' => 'BABAKAN MADANG'],
            ['regency_id' => $kabbogor->id, 'name' => 'JONGGOL'],
            ['regency_id' => $kabbogor->id, 'name' => 'CILEUNGSI'],
            ['regency_id' => $kabbogor->id, 'name' => 'CARIU'],
            ['regency_id' => $kabbogor->id, 'name' => 'SUKAMAKMUR'],
            ['regency_id' => $kabbogor->id, 'name' => 'PARUNG'],
            ['regency_id' => $kabbogor->id, 'name' => 'GUNUNG SINDUR'],
            ['regency_id' => $kabbogor->id, 'name' => 'KEMANG'],
            ['regency_id' => $kabbogor->id, 'name' => 'BOJONG GEDE'],
            ['regency_id' => $kabbogor->id, 'name' => 'LEUWILIANG'],
            ['regency_id' => $kabbogor->id, 'name' => 'CIAMPEA'],
            ['regency_id' => $kabbogor->id, 'name' => 'CIBUNGBULANG'],
            ['regency_id' => $kabbogor->id, 'name' => 'PAMIJAHAN'],
            ['regency_id' => $kabbogor->id, 'name' => 'RUMPIN'],
            ['regency_id' => $kabbogor->id, 'name' => 'JASINGA'],
            ['regency_id' => $kabbogor->id, 'name' => 'PARUNG PANJANG'],
            ['regency_id' => $kabbogor->id, 'name' => 'NANGGUNG'],
            ['regency_id' => $kabbogor->id, 'name' => 'CIGUDEG'],
            ['regency_id' => $kabbogor->id, 'name' => 'TENJO'],
            ['regency_id' => $kabbogor->id, 'name' => 'CIAWI'],
            ['regency_id' => $kabbogor->id, 'name' => 'CISARUA'],
            ['regency_id' => $kabbogor->id, 'name' => 'MEGAMENDUNG'],
            ['regency_id' => $kabbogor->id, 'name' => 'CARINGIN'],
            ['regency_id' => $kabbogor->id, 'name' => 'CIJERUK'],
            ['regency_id' => $kabbogor->id, 'name' => 'CIOMAS'],
            ['regency_id' => $kabbogor->id, 'name' => 'DRAMAGA'],
            ['regency_id' => $kabbogor->id, 'name' => 'TAMANSARI'],
            ['regency_id' => $kabbogor->id, 'name' => 'KLAPANUNGGAL'],
            ['regency_id' => $kabbogor->id, 'name' => 'CISEENG'],
            ['regency_id' => $kabbogor->id, 'name' => 'RANCA BUNGUR'],
            ['regency_id' => $kabbogor->id, 'name' => 'SUKAJAYA'],
            ['regency_id' => $kabbogor->id, 'name' => 'TANJUNGSARI'],
            ['regency_id' => $kabbogor->id, 'name' => 'TAJURHALANG'],
            ['regency_id' => $kabbogor->id, 'name' => 'CIGOMBONG'],
            ['regency_id' => $kabbogor->id, 'name' => 'LEUWISADENG'],
            ['regency_id' => $kabbogor->id, 'name' => 'TENJOLAYA'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'PALABUHANRATU'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'SIMPENAN'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'CIKAKAK'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'BANTARGADUNG'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'CISOLOK'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'CIKIDANG'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'LENGKONG'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'JAMPANGTENGAH'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'WARUNGKIARA'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'CIKEMBAR'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'CIBADAK'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'NAGRAK'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'PARUNGKUDA'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'BOJONGGENTENG'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'PARAKANSALAK'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'CICURUG'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'CIDAHU'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'KALAPANUNGGAL'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'KABANDUNGAN'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'WALURAN'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'JAMPANGKULON'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'CIEMAS'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'KALIBUNDER'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'SURADE'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'CIBITUNG'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'CIRACAP'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'GUNUNGGURUH'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'CICANTAYAN'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'CISAAT'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'KADUDAMPIT'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'CARINGIN'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'SUKABUMI'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'SUKARAJA'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'KEBONPEDES'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'CIREUNGHAS'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'SUKALARANG'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'PABUARAN'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'PURABAYA'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'NYALINDUNG'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'GEGERBITUNG'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'SAGARANTEN'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'CURUGKEMBAR'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'CIDOLOG'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'CIDADAP'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'TEGALBULEUD'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'CIMANGGU'],
            ['regency_id' => $kabsukabumi->id, 'name' => 'CIAMBAR'],
            ['regency_id' => $kabcianjur->id, 'name' => 'CIANJUR'],
            ['regency_id' => $kabcianjur->id, 'name' => 'WARUNGKONDANG'],
            ['regency_id' => $kabcianjur->id, 'name' => 'CIBEBER'],
            ['regency_id' => $kabcianjur->id, 'name' => 'CILAKU'],
            ['regency_id' => $kabcianjur->id, 'name' => 'CIRANJANG'],
            ['regency_id' => $kabcianjur->id, 'name' => 'BOJONGPICUNG'],
            ['regency_id' => $kabcianjur->id, 'name' => 'KARANGTENGAH'],
            ['regency_id' => $kabcianjur->id, 'name' => 'MANDE'],
            ['regency_id' => $kabcianjur->id, 'name' => 'SUKALUYU'],
            ['regency_id' => $kabcianjur->id, 'name' => 'PACET'],
            ['regency_id' => $kabcianjur->id, 'name' => 'CUGENANG'],
            ['regency_id' => $kabcianjur->id, 'name' => 'CIKALONGKULON'],
            ['regency_id' => $kabcianjur->id, 'name' => 'SUKARESMI'],
            ['regency_id' => $kabcianjur->id, 'name' => 'SUKANAGARA'],
            ['regency_id' => $kabcianjur->id, 'name' => 'CAMPAKA'],
            ['regency_id' => $kabcianjur->id, 'name' => 'TAKOKAK'],
            ['regency_id' => $kabcianjur->id, 'name' => 'KADUPANDAK'],
            ['regency_id' => $kabcianjur->id, 'name' => 'PAGELARAN'],
            ['regency_id' => $kabcianjur->id, 'name' => 'TANGGEUNG'],
            ['regency_id' => $kabcianjur->id, 'name' => 'CIBINONG'],
            ['regency_id' => $kabcianjur->id, 'name' => 'SINDANGBARANG'],
            ['regency_id' => $kabcianjur->id, 'name' => 'AGRABINTA'],
            ['regency_id' => $kabcianjur->id, 'name' => 'CIDAUN'],
            ['regency_id' => $kabcianjur->id, 'name' => 'NARINGGUL'],
            ['regency_id' => $kabcianjur->id, 'name' => 'CAMPAKAMULYA'],
            ['regency_id' => $kabcianjur->id, 'name' => 'CIKADU'],
            ['regency_id' => $kabcianjur->id, 'name' => 'GEKBRONG'],
            ['regency_id' => $kabcianjur->id, 'name' => 'CIPANAS'],
            ['regency_id' => $kabcianjur->id, 'name' => 'CIJATI'],
            ['regency_id' => $kabcianjur->id, 'name' => 'LELES'],
            ['regency_id' => $kabcianjur->id, 'name' => 'HAURWANGI'],
            ['regency_id' => $kabcianjur->id, 'name' => 'PASIRKUDA'],
            ['regency_id' => $kabbandung->id, 'name' => 'CILEUNYI'],
            ['regency_id' => $kabbandung->id, 'name' => 'CIMENYAN'],
            ['regency_id' => $kabbandung->id, 'name' => 'CILENGKRANG'],
            ['regency_id' => $kabbandung->id, 'name' => 'BOJONGSOANG'],
            ['regency_id' => $kabbandung->id, 'name' => 'MARGAHAYU'],
            ['regency_id' => $kabbandung->id, 'name' => 'MARGAASIH'],
            ['regency_id' => $kabbandung->id, 'name' => 'KATAPANG'],
            ['regency_id' => $kabbandung->id, 'name' => 'DAYEUHKOLOT'],
            ['regency_id' => $kabbandung->id, 'name' => 'BANJARAN'],
            ['regency_id' => $kabbandung->id, 'name' => 'PAMEUNGPEUK'],
            ['regency_id' => $kabbandung->id, 'name' => 'PANGALENGAN'],
            ['regency_id' => $kabbandung->id, 'name' => 'ARJASARI'],
            ['regency_id' => $kabbandung->id, 'name' => 'CIMAUNG'],
            ['regency_id' => $kabbandung->id, 'name' => 'CICALENGKA'],
            ['regency_id' => $kabbandung->id, 'name' => 'NAGREG'],
            ['regency_id' => $kabbandung->id, 'name' => 'CIKANCUNG'],
            ['regency_id' => $kabbandung->id, 'name' => 'RANCAEKEK'],
            ['regency_id' => $kabbandung->id, 'name' => 'CIPARAY'],
            ['regency_id' => $kabbandung->id, 'name' => 'PACET'],
            ['regency_id' => $kabbandung->id, 'name' => 'KERTASARI'],
            ['regency_id' => $kabbandung->id, 'name' => 'BALEENDAH'],
            ['regency_id' => $kabbandung->id, 'name' => 'MAJALAYA'],
            ['regency_id' => $kabbandung->id, 'name' => 'SOLOKANJERUK'],
            ['regency_id' => $kabbandung->id, 'name' => 'PASEH'],
            ['regency_id' => $kabbandung->id, 'name' => 'IBUN'],
            ['regency_id' => $kabbandung->id, 'name' => 'SOREANG'],
            ['regency_id' => $kabbandung->id, 'name' => 'PASIRJAMBU'],
            ['regency_id' => $kabbandung->id, 'name' => 'CIWIDEY'],
            ['regency_id' => $kabbandung->id, 'name' => 'RANCABALI'],
            ['regency_id' => $kabbandung->id, 'name' => 'CANGKUANG'],
            ['regency_id' => $kabbandung->id, 'name' => 'KUTAWARINGIN'],
            ['regency_id' => $kabgarut->id, 'name' => 'GARUT KOTA'],
            ['regency_id' => $kabgarut->id, 'name' => 'KARANGPAWITAN'],
            ['regency_id' => $kabgarut->id, 'name' => 'WANARAJA'],
            ['regency_id' => $kabgarut->id, 'name' => 'TAROGONG KALER'],
            ['regency_id' => $kabgarut->id, 'name' => 'TAROGONG KIDUL'],
            ['regency_id' => $kabgarut->id, 'name' => 'BANYURESMI'],
            ['regency_id' => $kabgarut->id, 'name' => 'SAMARANG'],
            ['regency_id' => $kabgarut->id, 'name' => 'PASIRWANGI'],
            ['regency_id' => $kabgarut->id, 'name' => 'LELES'],
            ['regency_id' => $kabgarut->id, 'name' => 'KADUNGORA'],
            ['regency_id' => $kabgarut->id, 'name' => 'LEUWIGOONG'],
            ['regency_id' => $kabgarut->id, 'name' => 'CIBATU'],
            ['regency_id' => $kabgarut->id, 'name' => 'KERSAMANAH'],
            ['regency_id' => $kabgarut->id, 'name' => 'MALANGBONG'],
            ['regency_id' => $kabgarut->id, 'name' => 'SUKAWENING'],
            ['regency_id' => $kabgarut->id, 'name' => 'KARANGTENGAH'],
            ['regency_id' => $kabgarut->id, 'name' => 'BAYONGBONG'],
            ['regency_id' => $kabgarut->id, 'name' => 'CIGEDUG'],
            ['regency_id' => $kabgarut->id, 'name' => 'CILAWU'],
            ['regency_id' => $kabgarut->id, 'name' => 'CISURUPAN'],
            ['regency_id' => $kabgarut->id, 'name' => 'SUKARESMI'],
            ['regency_id' => $kabgarut->id, 'name' => 'CIKAJANG'],
            ['regency_id' => $kabgarut->id, 'name' => 'BANJARWANGI'],
            ['regency_id' => $kabgarut->id, 'name' => 'SINGAJAYA'],
            ['regency_id' => $kabgarut->id, 'name' => 'CIHURIP'],
            ['regency_id' => $kabgarut->id, 'name' => 'PEUNDEUY'],
            ['regency_id' => $kabgarut->id, 'name' => 'PAMEUNGPEUK'],
            ['regency_id' => $kabgarut->id, 'name' => 'CISOMPET'],
            ['regency_id' => $kabgarut->id, 'name' => 'CIBALONG'],
            ['regency_id' => $kabgarut->id, 'name' => 'CIKELET'],
            ['regency_id' => $kabgarut->id, 'name' => 'BUNGBULANG'],
            ['regency_id' => $kabgarut->id, 'name' => 'MEKARMUKTI'],
            ['regency_id' => $kabgarut->id, 'name' => 'PAKENJENG'],
            ['regency_id' => $kabgarut->id, 'name' => 'PAMULIHAN'],
            ['regency_id' => $kabgarut->id, 'name' => 'CISEWU'],
            ['regency_id' => $kabgarut->id, 'name' => 'CARINGIN'],
            ['regency_id' => $kabgarut->id, 'name' => 'TALEGONG'],
            ['regency_id' => $kabgarut->id, 'name' => 'LIMBANGAN'],
            ['regency_id' => $kabgarut->id, 'name' => 'SELAAWI'],
            ['regency_id' => $kabgarut->id, 'name' => 'CIBIUK'],
            ['regency_id' => $kabgarut->id, 'name' => 'PANGATIKAN'],
            ['regency_id' => $kabgarut->id, 'name' => 'SUCINARAJA'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'CIPATUJAH'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'KARANGNUNGGAL'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'CIKALONG'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'PANCATENGAH'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'CIKATOMAS'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'CIBALONG'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'PARUNGPONTENG'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'BANTARKALONG'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'BOJONGASIH'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'CULAMEGA'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'BOJONGGAMBIR'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'SODONGHILIR'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'TARAJU'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'SALAWU'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'PUSPAHIANG'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'TANJUNGJAYA'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'SUKARAJA'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'SALOPA'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'JATIWARAS'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'CINEAM'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'KARANG JAYA'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'MANONJAYA'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'GUNUNG TANJUNG'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'SINGAPARNA'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'MANGUNREJA'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'SUKARAME'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'CIGALONTANG'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'LEUWISARI'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'PADAKEMBANG'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'SARIWANGI'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'SUKARATU'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'CISAYONG'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'SUKAHENING'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'RAJAPOLAH'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'JAMANIS'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'CIAWI'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'KADIPATEN'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'PAGERAGEUNG'],
            ['regency_id' => $kabtasikmalaya->id, 'name' => 'SUKARESIK'],
            ['regency_id' => $kabciamis->id, 'name' => 'CIAMIS'],
            ['regency_id' => $kabciamis->id, 'name' => 'CIKONENG'],
            ['regency_id' => $kabciamis->id, 'name' => 'CIJEUNGJING'],
            ['regency_id' => $kabciamis->id, 'name' => 'SADANANYA'],
            ['regency_id' => $kabciamis->id, 'name' => 'CIDOLOG'],
            ['regency_id' => $kabciamis->id, 'name' => 'CIHAURBEUTI'],
            ['regency_id' => $kabciamis->id, 'name' => 'PANUMBANGAN'],
            ['regency_id' => $kabciamis->id, 'name' => 'PANJALU'],
            ['regency_id' => $kabciamis->id, 'name' => 'KAWALI'],
            ['regency_id' => $kabciamis->id, 'name' => 'PANAWANGAN'],
            ['regency_id' => $kabciamis->id, 'name' => 'CIPAKU'],
            ['regency_id' => $kabciamis->id, 'name' => 'JATINAGARA'],
            ['regency_id' => $kabciamis->id, 'name' => 'RAJADESA'],
            ['regency_id' => $kabciamis->id, 'name' => 'SUKADANA'],
            ['regency_id' => $kabciamis->id, 'name' => 'RANCAH'],
            ['regency_id' => $kabciamis->id, 'name' => 'TAMBAKSARI'],
            ['regency_id' => $kabciamis->id, 'name' => 'LAKBOK'],
            ['regency_id' => $kabciamis->id, 'name' => 'BANJARSARI'],
            ['regency_id' => $kabciamis->id, 'name' => 'PAMARICAN'],
            ['regency_id' => $kabciamis->id, 'name' => 'CIMARAGAS'],
            ['regency_id' => $kabciamis->id, 'name' => 'CISAGA'],
            ['regency_id' => $kabciamis->id, 'name' => 'SINDANGKASIH'],
            ['regency_id' => $kabciamis->id, 'name' => 'BAREGBEG'],
            ['regency_id' => $kabciamis->id, 'name' => 'SUKAMANTRI'],
            ['regency_id' => $kabciamis->id, 'name' => 'LUMBUNG'],
            ['regency_id' => $kabciamis->id, 'name' => 'PURWADADI'],
            ['regency_id' => $kabciamis->id, 'name' => 'BANJARANYAR'],
            ['regency_id' => $kabkuningan->id, 'name' => 'KADUGEDE'],
            ['regency_id' => $kabkuningan->id, 'name' => 'CINIRU'],
            ['regency_id' => $kabkuningan->id, 'name' => 'SUBANG'],
            ['regency_id' => $kabkuningan->id, 'name' => 'CIWARU'],
            ['regency_id' => $kabkuningan->id, 'name' => 'CIBINGBIN'],
            ['regency_id' => $kabkuningan->id, 'name' => 'LURAGUNG'],
            ['regency_id' => $kabkuningan->id, 'name' => 'LEBAKWANGI'],
            ['regency_id' => $kabkuningan->id, 'name' => 'GARAWANGI'],
            ['regency_id' => $kabkuningan->id, 'name' => 'KUNINGAN'],
            ['regency_id' => $kabkuningan->id, 'name' => 'CIAWIGEBANG'],
            ['regency_id' => $kabkuningan->id, 'name' => 'CIDAHU'],
            ['regency_id' => $kabkuningan->id, 'name' => 'JALAKSANA'],
            ['regency_id' => $kabkuningan->id, 'name' => 'CILIMUS'],
            ['regency_id' => $kabkuningan->id, 'name' => 'MANDIRANCAN'],
            ['regency_id' => $kabkuningan->id, 'name' => 'SELAJAMBE'],
            ['regency_id' => $kabkuningan->id, 'name' => 'KRAMATMULYA'],
            ['regency_id' => $kabkuningan->id, 'name' => 'DARMA'],
            ['regency_id' => $kabkuningan->id, 'name' => 'CIGUGUR'],
            ['regency_id' => $kabkuningan->id, 'name' => 'PASAWAHAN'],
            ['regency_id' => $kabkuningan->id, 'name' => 'NUSAHERANG'],
            ['regency_id' => $kabkuningan->id, 'name' => 'CIPICUNG'],
            ['regency_id' => $kabkuningan->id, 'name' => 'PANCALANG'],
            ['regency_id' => $kabkuningan->id, 'name' => 'JAPARA'],
            ['regency_id' => $kabkuningan->id, 'name' => 'CIMAHI'],
            ['regency_id' => $kabkuningan->id, 'name' => 'CILEBAK'],
            ['regency_id' => $kabkuningan->id, 'name' => 'HANTARA'],
            ['regency_id' => $kabkuningan->id, 'name' => 'KALIMANGGIS'],
            ['regency_id' => $kabkuningan->id, 'name' => 'CIBEUREUM'],
            ['regency_id' => $kabkuningan->id, 'name' => 'KARANG KANCANA'],
            ['regency_id' => $kabkuningan->id, 'name' => 'MALEBER'],
            ['regency_id' => $kabkuningan->id, 'name' => 'SINDANG AGUNG'],
            ['regency_id' => $kabkuningan->id, 'name' => 'CIGANDAMEKAR'],
            ['regency_id' => $kabcirebon->id, 'name' => 'WALED'],
            ['regency_id' => $kabcirebon->id, 'name' => 'CILEDUG'],
            ['regency_id' => $kabcirebon->id, 'name' => 'LOSARI'],
            ['regency_id' => $kabcirebon->id, 'name' => 'PABEDILAN'],
            ['regency_id' => $kabcirebon->id, 'name' => 'BABAKAN'],
            ['regency_id' => $kabcirebon->id, 'name' => 'KARANGSEMBUNG'],
            ['regency_id' => $kabcirebon->id, 'name' => 'LEMAHABANG'],
            ['regency_id' => $kabcirebon->id, 'name' => 'SUSUKAN LEBAK'],
            ['regency_id' => $kabcirebon->id, 'name' => 'SEDONG'],
            ['regency_id' => $kabcirebon->id, 'name' => 'ASTANAJAPURA'],
            ['regency_id' => $kabcirebon->id, 'name' => 'PANGENAN'],
            ['regency_id' => $kabcirebon->id, 'name' => 'MUNDU'],
            ['regency_id' => $kabcirebon->id, 'name' => 'BEBER'],
            ['regency_id' => $kabcirebon->id, 'name' => 'TALUN'],
            ['regency_id' => $kabcirebon->id, 'name' => 'SUMBER'],
            ['regency_id' => $kabcirebon->id, 'name' => 'DUKUPUNTANG'],
            ['regency_id' => $kabcirebon->id, 'name' => 'PALIMANAN'],
            ['regency_id' => $kabcirebon->id, 'name' => 'PLUMBON'],
            ['regency_id' => $kabcirebon->id, 'name' => 'WERU'],
            ['regency_id' => $kabcirebon->id, 'name' => 'KEDAWUNG'],
            ['regency_id' => $kabcirebon->id, 'name' => 'GUNUNG JATI'],
            ['regency_id' => $kabcirebon->id, 'name' => 'KAPETAKAN'],
            ['regency_id' => $kabcirebon->id, 'name' => 'KLANGENAN'],
            ['regency_id' => $kabcirebon->id, 'name' => 'ARJAWINANGUN'],
            ['regency_id' => $kabcirebon->id, 'name' => 'PANGURAGAN'],
            ['regency_id' => $kabcirebon->id, 'name' => 'CIWARINGIN'],
            ['regency_id' => $kabcirebon->id, 'name' => 'SUSUKAN'],
            ['regency_id' => $kabcirebon->id, 'name' => 'GEGESIK'],
            ['regency_id' => $kabcirebon->id, 'name' => 'KALIWEDI'],
            ['regency_id' => $kabcirebon->id, 'name' => 'GEBANG'],
            ['regency_id' => $kabcirebon->id, 'name' => 'DEPOK'],
            ['regency_id' => $kabcirebon->id, 'name' => 'PASALEMAN'],
            ['regency_id' => $kabcirebon->id, 'name' => 'PABUARAN'],
            ['regency_id' => $kabcirebon->id, 'name' => 'KARANGWARENG'],
            ['regency_id' => $kabcirebon->id, 'name' => 'TENGAH TANI'],
            ['regency_id' => $kabcirebon->id, 'name' => 'PLERED'],
            ['regency_id' => $kabcirebon->id, 'name' => 'GEMPOL'],
            ['regency_id' => $kabcirebon->id, 'name' => 'GREGED'],
            ['regency_id' => $kabcirebon->id, 'name' => 'SURANENGGALA'],
            ['regency_id' => $kabcirebon->id, 'name' => 'JAMBLANG'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'LEMAHSUGIH'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'BANTARUJEG'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'CIKIJING'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'TALAGA'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'ARGAPURA'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'MAJA'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'MAJALENGKA'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'SUKAHAJI'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'RAJAGALUH'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'LEUWIMUNDING'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'JATIWANGI'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'DAWUAN'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'KADIPATEN'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'KERTAJATI'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'JATITUJUH'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'LIGUNG'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'SUMBERJAYA'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'PANYINGKIRAN'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'PALASAH'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'CIGASONG'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'SINDANGWANGI'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'BANJARAN'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'CINGAMBUL'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'KASOKANDEL'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'SINDANG'],
            ['regency_id' => $kabmajalengka->id, 'name' => 'MALAUSMA'],
            ['regency_id' => $kabsumedang->id, 'name' => 'WADO'],
            ['regency_id' => $kabsumedang->id, 'name' => 'JATINUNGGAL'],
            ['regency_id' => $kabsumedang->id, 'name' => 'DARMARAJA'],
            ['regency_id' => $kabsumedang->id, 'name' => 'CIBUGEL'],
            ['regency_id' => $kabsumedang->id, 'name' => 'CISITU'],
            ['regency_id' => $kabsumedang->id, 'name' => 'SITURAJA'],
            ['regency_id' => $kabsumedang->id, 'name' => 'CONGGEANG'],
            ['regency_id' => $kabsumedang->id, 'name' => 'PASEH'],
            ['regency_id' => $kabsumedang->id, 'name' => 'SURIAN'],
            ['regency_id' => $kabsumedang->id, 'name' => 'BUAHDUA'],
            ['regency_id' => $kabsumedang->id, 'name' => 'TANJUNGSARI'],
            ['regency_id' => $kabsumedang->id, 'name' => 'SUKASARI'],
            ['regency_id' => $kabsumedang->id, 'name' => 'PAMULIHAN'],
            ['regency_id' => $kabsumedang->id, 'name' => 'CIMANGGUNG'],
            ['regency_id' => $kabsumedang->id, 'name' => 'JATINANGOR'],
            ['regency_id' => $kabsumedang->id, 'name' => 'RANCAKALONG'],
            ['regency_id' => $kabsumedang->id, 'name' => 'SUMEDANG SELATAN'],
            ['regency_id' => $kabsumedang->id, 'name' => 'SUMEDANG UTARA'],
            ['regency_id' => $kabsumedang->id, 'name' => 'GANEAS'],
            ['regency_id' => $kabsumedang->id, 'name' => 'TANJUNGKERTA'],
            ['regency_id' => $kabsumedang->id, 'name' => 'TANJUNGMEDAR'],
            ['regency_id' => $kabsumedang->id, 'name' => 'CIMALAKA'],
            ['regency_id' => $kabsumedang->id, 'name' => 'CISARUA'],
            ['regency_id' => $kabsumedang->id, 'name' => 'TOMO'],
            ['regency_id' => $kabsumedang->id, 'name' => 'UJUNGJAYA'],
            ['regency_id' => $kabsumedang->id, 'name' => 'JATIGEDE'],
            ['regency_id' => $kabindramayu->id, 'name' => 'HAURGEULIS'],
            ['regency_id' => $kabindramayu->id, 'name' => 'KROYA'],
            ['regency_id' => $kabindramayu->id, 'name' => 'GABUSWETAN'],
            ['regency_id' => $kabindramayu->id, 'name' => 'CIKEDUNG'],
            ['regency_id' => $kabindramayu->id, 'name' => 'LELEA'],
            ['regency_id' => $kabindramayu->id, 'name' => 'BANGODUA'],
            ['regency_id' => $kabindramayu->id, 'name' => 'WIDASARI'],
            ['regency_id' => $kabindramayu->id, 'name' => 'KERTASEMAYA'],
            ['regency_id' => $kabindramayu->id, 'name' => 'KRANGKENG'],
            ['regency_id' => $kabindramayu->id, 'name' => 'KARANGAMPEL'],
            ['regency_id' => $kabindramayu->id, 'name' => 'JUNTINYUAT'],
            ['regency_id' => $kabindramayu->id, 'name' => 'SLIYEG'],
            ['regency_id' => $kabindramayu->id, 'name' => 'JATIBARANG'],
            ['regency_id' => $kabindramayu->id, 'name' => 'BALONGAN'],
            ['regency_id' => $kabindramayu->id, 'name' => 'INDRAMAYU'],
            ['regency_id' => $kabindramayu->id, 'name' => 'SINDANG'],
            ['regency_id' => $kabindramayu->id, 'name' => 'CANTIGI'],
            ['regency_id' => $kabindramayu->id, 'name' => 'LOHBENER'],
            ['regency_id' => $kabindramayu->id, 'name' => 'ARAHAN'],
            ['regency_id' => $kabindramayu->id, 'name' => 'LOSARANG'],
            ['regency_id' => $kabindramayu->id, 'name' => 'KANDANGHAUR'],
            ['regency_id' => $kabindramayu->id, 'name' => 'BONGAS'],
            ['regency_id' => $kabindramayu->id, 'name' => 'ANJATAN'],
            ['regency_id' => $kabindramayu->id, 'name' => 'SUKRA'],
            ['regency_id' => $kabindramayu->id, 'name' => 'GANTAR'],
            ['regency_id' => $kabindramayu->id, 'name' => 'TRISI'],
            ['regency_id' => $kabindramayu->id, 'name' => 'SUKAGUMIWANG'],
            ['regency_id' => $kabindramayu->id, 'name' => 'KEDOKAN BUNDER'],
            ['regency_id' => $kabindramayu->id, 'name' => 'PASEKAN'],
            ['regency_id' => $kabindramayu->id, 'name' => 'TUKDANA'],
            ['regency_id' => $kabindramayu->id, 'name' => 'PATROL'],
            ['regency_id' => $kabsubang->id, 'name' => 'SAGALAHERANG'],
            ['regency_id' => $kabsubang->id, 'name' => 'CISALAK'],
            ['regency_id' => $kabsubang->id, 'name' => 'SUBANG'],
            ['regency_id' => $kabsubang->id, 'name' => 'KALIJATI'],
            ['regency_id' => $kabsubang->id, 'name' => 'PABUARAN'],
            ['regency_id' => $kabsubang->id, 'name' => 'PURWADADI'],
            ['regency_id' => $kabsubang->id, 'name' => 'PAGADEN'],
            ['regency_id' => $kabsubang->id, 'name' => 'BINONG'],
            ['regency_id' => $kabsubang->id, 'name' => 'CIASEM'],
            ['regency_id' => $kabsubang->id, 'name' => 'PUSAKANAGARA'],
            ['regency_id' => $kabsubang->id, 'name' => 'PAMANUKAN'],
            ['regency_id' => $kabsubang->id, 'name' => 'JALANCAGAK'],
            ['regency_id' => $kabsubang->id, 'name' => 'BLANAKAN'],
            ['regency_id' => $kabsubang->id, 'name' => 'TANJUNGSIANG'],
            ['regency_id' => $kabsubang->id, 'name' => 'COMPRENG'],
            ['regency_id' => $kabsubang->id, 'name' => 'PATOKBEUSI'],
            ['regency_id' => $kabsubang->id, 'name' => 'CIBOGO'],
            ['regency_id' => $kabsubang->id, 'name' => 'CIPUNAGARA'],
            ['regency_id' => $kabsubang->id, 'name' => 'CIJAMBE'],
            ['regency_id' => $kabsubang->id, 'name' => 'CIPEUNDEUY'],
            ['regency_id' => $kabsubang->id, 'name' => 'LEGONKULON'],
            ['regency_id' => $kabsubang->id, 'name' => 'CIKAUM'],
            ['regency_id' => $kabsubang->id, 'name' => 'SERANGPANJANG'],
            ['regency_id' => $kabsubang->id, 'name' => 'SUKASARI'],
            ['regency_id' => $kabsubang->id, 'name' => 'TAMBAKDAHAN'],
            ['regency_id' => $kabsubang->id, 'name' => 'KASOMALANG'],
            ['regency_id' => $kabsubang->id, 'name' => 'DAWUAN'],
            ['regency_id' => $kabsubang->id, 'name' => 'PAGADEN BARAT'],
            ['regency_id' => $kabsubang->id, 'name' => 'CIATER'],
            ['regency_id' => $kabsubang->id, 'name' => 'PUSAKAJAYA'],
            ['regency_id' => $kabpurwakarta->id, 'name' => 'PURWAKARTA'],
            ['regency_id' => $kabpurwakarta->id, 'name' => 'CAMPAKA'],
            ['regency_id' => $kabpurwakarta->id, 'name' => 'JATILUHUR'],
            ['regency_id' => $kabpurwakarta->id, 'name' => 'PLERED'],
            ['regency_id' => $kabpurwakarta->id, 'name' => 'SUKATANI'],
            ['regency_id' => $kabpurwakarta->id, 'name' => 'DARANGDAN'],
            ['regency_id' => $kabpurwakarta->id, 'name' => 'MANIIS'],
            ['regency_id' => $kabpurwakarta->id, 'name' => 'TEGALWARU'],
            ['regency_id' => $kabpurwakarta->id, 'name' => 'WANAYASA'],
            ['regency_id' => $kabpurwakarta->id, 'name' => 'PASAWAHAN'],
            ['regency_id' => $kabpurwakarta->id, 'name' => 'BOJONG'],
            ['regency_id' => $kabpurwakarta->id, 'name' => 'BABAKANCIKAO'],
            ['regency_id' => $kabpurwakarta->id, 'name' => 'BUNGURSARI'],
            ['regency_id' => $kabpurwakarta->id, 'name' => 'CIBATU'],
            ['regency_id' => $kabpurwakarta->id, 'name' => 'SUKASARI'],
            ['regency_id' => $kabpurwakarta->id, 'name' => 'PONDOKSALAM'],
            ['regency_id' => $kabpurwakarta->id, 'name' => 'KIARAPEDES'],
            ['regency_id' => $kabkarawang->id, 'name' => 'KARAWANG BARAT'],
            ['regency_id' => $kabkarawang->id, 'name' => 'PANGKALAN'],
            ['regency_id' => $kabkarawang->id, 'name' => 'TELUKJAMBE TIMUR'],
            ['regency_id' => $kabkarawang->id, 'name' => 'CIAMPEL'],
            ['regency_id' => $kabkarawang->id, 'name' => 'KLARI'],
            ['regency_id' => $kabkarawang->id, 'name' => 'RENGASDENGKLOK'],
            ['regency_id' => $kabkarawang->id, 'name' => 'KUTAWALUYA'],
            ['regency_id' => $kabkarawang->id, 'name' => 'BATUJAYA'],
            ['regency_id' => $kabkarawang->id, 'name' => 'TIRTAJAYA'],
            ['regency_id' => $kabkarawang->id, 'name' => 'PEDES'],
            ['regency_id' => $kabkarawang->id, 'name' => 'CIBUAYA'],
            ['regency_id' => $kabkarawang->id, 'name' => 'PAKISJAYA'],
            ['regency_id' => $kabkarawang->id, 'name' => 'CIKAMPEK'],
            ['regency_id' => $kabkarawang->id, 'name' => 'JATISARI'],
            ['regency_id' => $kabkarawang->id, 'name' => 'CILAMAYA WETAN'],
            ['regency_id' => $kabkarawang->id, 'name' => 'TIRTAMULYA'],
            ['regency_id' => $kabkarawang->id, 'name' => 'TELAGASARI'],
            ['regency_id' => $kabkarawang->id, 'name' => 'RAWAMERTA'],
            ['regency_id' => $kabkarawang->id, 'name' => 'LEMAHABANG'],
            ['regency_id' => $kabkarawang->id, 'name' => 'TEMPURAN'],
            ['regency_id' => $kabkarawang->id, 'name' => 'MAJALAYA'],
            ['regency_id' => $kabkarawang->id, 'name' => 'JAYAKERTA'],
            ['regency_id' => $kabkarawang->id, 'name' => 'CILAMAYA KULON'],
            ['regency_id' => $kabkarawang->id, 'name' => 'BANYUSARI'],
            ['regency_id' => $kabkarawang->id, 'name' => 'KOTA BARU'],
            ['regency_id' => $kabkarawang->id, 'name' => 'KARAWANG TIMUR'],
            ['regency_id' => $kabkarawang->id, 'name' => 'TELUKJAMBE BARAT'],
            ['regency_id' => $kabkarawang->id, 'name' => 'TEGALWARU'],
            ['regency_id' => $kabkarawang->id, 'name' => 'PURWASARI'],
            ['regency_id' => $kabkarawang->id, 'name' => 'CILEBAR'],
            ['regency_id' => $kabbekasi->id, 'name' => 'TARUMAJAYA'],
            ['regency_id' => $kabbekasi->id, 'name' => 'BABELAN'],
            ['regency_id' => $kabbekasi->id, 'name' => 'SUKAWANGI'],
            ['regency_id' => $kabbekasi->id, 'name' => 'TAMBELANG'],
            ['regency_id' => $kabbekasi->id, 'name' => 'TAMBUN UTARA'],
            ['regency_id' => $kabbekasi->id, 'name' => 'TAMBUN SELATAN'],
            ['regency_id' => $kabbekasi->id, 'name' => 'CIBITUNG'],
            ['regency_id' => $kabbekasi->id, 'name' => 'CIKARANG BARAT'],
            ['regency_id' => $kabbekasi->id, 'name' => 'CIKARANG UTARA'],
            ['regency_id' => $kabbekasi->id, 'name' => 'KARANG BAHAGIA'],
            ['regency_id' => $kabbekasi->id, 'name' => 'CIKARANG TIMUR'],
            ['regency_id' => $kabbekasi->id, 'name' => 'KEDUNG WARINGIN'],
            ['regency_id' => $kabbekasi->id, 'name' => 'PEBAYURAN'],
            ['regency_id' => $kabbekasi->id, 'name' => 'SUKAKARYA'],
            ['regency_id' => $kabbekasi->id, 'name' => 'SUKATANI'],
            ['regency_id' => $kabbekasi->id, 'name' => 'CABANGBUNGIN'],
            ['regency_id' => $kabbekasi->id, 'name' => 'MUARAGEMBONG'],
            ['regency_id' => $kabbekasi->id, 'name' => 'SETU'],
            ['regency_id' => $kabbekasi->id, 'name' => 'CIKARANG SELATAN'],
            ['regency_id' => $kabbekasi->id, 'name' => 'CIKARANG PUSAT'],
            ['regency_id' => $kabbekasi->id, 'name' => 'SERANG BARU'],
            ['regency_id' => $kabbekasi->id, 'name' => 'CIBARUSAH'],
            ['regency_id' => $kabbekasi->id, 'name' => 'BOJONGMANGU'],
            ['regency_id' => $kabbandungbarat->id, 'name' => 'LEMBANG'],
            ['regency_id' => $kabbandungbarat->id, 'name' => 'PARONGPONG'],
            ['regency_id' => $kabbandungbarat->id, 'name' => 'CISARUA'],
            ['regency_id' => $kabbandungbarat->id, 'name' => 'CIKALONGWETAN'],
            ['regency_id' => $kabbandungbarat->id, 'name' => 'CIPEUNDEUY'],
            ['regency_id' => $kabbandungbarat->id, 'name' => 'NGAMPRAH'],
            ['regency_id' => $kabbandungbarat->id, 'name' => 'CIPATAT'],
            ['regency_id' => $kabbandungbarat->id, 'name' => 'PADALARANG'],
            ['regency_id' => $kabbandungbarat->id, 'name' => 'BATUJAJAR'],
            ['regency_id' => $kabbandungbarat->id, 'name' => 'CIHAMPELAS'],
            ['regency_id' => $kabbandungbarat->id, 'name' => 'CILILIN'],
            ['regency_id' => $kabbandungbarat->id, 'name' => 'CIPONGKOR'],
            ['regency_id' => $kabbandungbarat->id, 'name' => 'RONGGA'],
            ['regency_id' => $kabbandungbarat->id, 'name' => 'SINDANGKERTA'],
            ['regency_id' => $kabbandungbarat->id, 'name' => 'GUNUNGHALU'],
            ['regency_id' => $kabbandungbarat->id, 'name' => 'SAGULING'],
            ['regency_id' => $kabpangandaran->id, 'name' => 'PARIGI'],
            ['regency_id' => $kabpangandaran->id, 'name' => 'CIJULANG'],
            ['regency_id' => $kabpangandaran->id, 'name' => 'CIMERAK'],
            ['regency_id' => $kabpangandaran->id, 'name' => 'CIGUGUR'],
            ['regency_id' => $kabpangandaran->id, 'name' => 'LANGKAPLANCAR'],
            ['regency_id' => $kabpangandaran->id, 'name' => 'MANGUNJAYA'],
            ['regency_id' => $kabpangandaran->id, 'name' => 'PADAHERANG'],
            ['regency_id' => $kabpangandaran->id, 'name' => 'KALIPUCANG'],
            ['regency_id' => $kabpangandaran->id, 'name' => 'PANGANDARAN'],
            ['regency_id' => $kabpangandaran->id, 'name' => 'SIDAMULIH'],
            ['regency_id' => $kotabogor->id, 'name' => 'BOGOR SELATAN'],
            ['regency_id' => $kotabogor->id, 'name' => 'BOGOR TIMUR'],
            ['regency_id' => $kotabogor->id, 'name' => 'BOGOR TENGAH'],
            ['regency_id' => $kotabogor->id, 'name' => 'BOGOR BARAT'],
            ['regency_id' => $kotabogor->id, 'name' => 'BOGOR UTARA'],
            ['regency_id' => $kotabogor->id, 'name' => 'TANAH SAREAL'],
            ['regency_id' => $kotasukabumi->id, 'name' => 'GUNUNGPUYUH'],
            ['regency_id' => $kotasukabumi->id, 'name' => 'CIKOLE'],
            ['regency_id' => $kotasukabumi->id, 'name' => 'CITAMIANG'],
            ['regency_id' => $kotasukabumi->id, 'name' => 'WARUDOYONG'],
            ['regency_id' => $kotasukabumi->id, 'name' => 'BAROS'],
            ['regency_id' => $kotasukabumi->id, 'name' => 'LEMBURSITU'],
            ['regency_id' => $kotasukabumi->id, 'name' => 'CIBEUREUM'],
            ['regency_id' => $kotabandung->id, 'name' => 'SUKASARI'],
            ['regency_id' => $kotabandung->id, 'name' => 'COBLONG'],
            ['regency_id' => $kotabandung->id, 'name' => 'BABAKAN CIPARAY'],
            ['regency_id' => $kotabandung->id, 'name' => 'BOJONGLOA KALER'],
            ['regency_id' => $kotabandung->id, 'name' => 'ANDIR'],
            ['regency_id' => $kotabandung->id, 'name' => 'CICENDO'],
            ['regency_id' => $kotabandung->id, 'name' => 'SUKAJADI'],
            ['regency_id' => $kotabandung->id, 'name' => 'CIDADAP'],
            ['regency_id' => $kotabandung->id, 'name' => 'BANDUNG WETAN'],
            ['regency_id' => $kotabandung->id, 'name' => 'ASTANA ANYAR'],
            ['regency_id' => $kotabandung->id, 'name' => 'REGOL'],
            ['regency_id' => $kotabandung->id, 'name' => 'BATUNUNGGAL'],
            ['regency_id' => $kotabandung->id, 'name' => 'LENGKONG'],
            ['regency_id' => $kotabandung->id, 'name' => 'CIBEUNYING KIDUL'],
            ['regency_id' => $kotabandung->id, 'name' => 'BANDUNG KULON'],
            ['regency_id' => $kotabandung->id, 'name' => 'KIARACONDONG'],
            ['regency_id' => $kotabandung->id, 'name' => 'BOJONGLOA KIDUL'],
            ['regency_id' => $kotabandung->id, 'name' => 'CIBEUNYING KALER'],
            ['regency_id' => $kotabandung->id, 'name' => 'SUMUR BANDUNG'],
            ['regency_id' => $kotabandung->id, 'name' => 'ANTAPANI'],
            ['regency_id' => $kotabandung->id, 'name' => 'BANDUNG KIDUL'],
            ['regency_id' => $kotabandung->id, 'name' => 'BUAHBATU'],
            ['regency_id' => $kotabandung->id, 'name' => 'RANCASARI'],
            ['regency_id' => $kotabandung->id, 'name' => 'ARCAMANIK'],
            ['regency_id' => $kotabandung->id, 'name' => 'CIBIRU'],
            ['regency_id' => $kotabandung->id, 'name' => 'UJUNGBERUNG'],
            ['regency_id' => $kotabandung->id, 'name' => 'GEDEBAGE'],
            ['regency_id' => $kotabandung->id, 'name' => 'PANYILEUKAN'],
            ['regency_id' => $kotabandung->id, 'name' => 'CINAMBO'],
            ['regency_id' => $kotabandung->id, 'name' => 'MANDALAJATI'],
            ['regency_id' => $kotacirebon->id, 'name' => 'KEJAKSAN'],
            ['regency_id' => $kotacirebon->id, 'name' => 'LEMAH WUNGKUK'],
            ['regency_id' => $kotacirebon->id, 'name' => 'HARJAMUKTI'],
            ['regency_id' => $kotacirebon->id, 'name' => 'PEKALIPAN'],
            ['regency_id' => $kotacirebon->id, 'name' => 'KESAMBI'],
            ['regency_id' => $kotabekasi->id, 'name' => 'BEKASI TIMUR'],
            ['regency_id' => $kotabekasi->id, 'name' => 'BEKASI BARAT'],
            ['regency_id' => $kotabekasi->id, 'name' => 'BEKASI UTARA'],
            ['regency_id' => $kotabekasi->id, 'name' => 'BEKASI SELATAN'],
            ['regency_id' => $kotabekasi->id, 'name' => 'RAWALUMBU'],
            ['regency_id' => $kotabekasi->id, 'name' => 'MEDANSATRIA'],
            ['regency_id' => $kotabekasi->id, 'name' => 'BANTARGEBANG'],
            ['regency_id' => $kotabekasi->id, 'name' => 'PONDOKGEDE'],
            ['regency_id' => $kotabekasi->id, 'name' => 'JATIASIH'],
            ['regency_id' => $kotabekasi->id, 'name' => 'JATISAMPURNA'],
            ['regency_id' => $kotabekasi->id, 'name' => 'MUSTIKAJAYA'],
            ['regency_id' => $kotabekasi->id, 'name' => 'PONDOKMELATI'],
            ['regency_id' => $kotadepok->id, 'name' => 'PANCORAN MAS'],
            ['regency_id' => $kotadepok->id, 'name' => 'CIMANGGIS'],
            ['regency_id' => $kotadepok->id, 'name' => 'SAWANGAN'],
            ['regency_id' => $kotadepok->id, 'name' => 'LIMO'],
            ['regency_id' => $kotadepok->id, 'name' => 'SUKMAJAYA'],
            ['regency_id' => $kotadepok->id, 'name' => 'BEJI'],
            ['regency_id' => $kotadepok->id, 'name' => 'CIPAYUNG'],
            ['regency_id' => $kotadepok->id, 'name' => 'CILODONG'],
            ['regency_id' => $kotadepok->id, 'name' => 'CINERE'],
            ['regency_id' => $kotadepok->id, 'name' => 'TAPOS'],
            ['regency_id' => $kotadepok->id, 'name' => 'BOJONGSARI'],
            ['regency_id' => $kotacimahi->id, 'name' => 'CIMAHI SELATAN'],
            ['regency_id' => $kotacimahi->id, 'name' => 'CIMAHI TENGAH'],
            ['regency_id' => $kotacimahi->id, 'name' => 'CIMAHI UTARA'],
            ['regency_id' => $kotatasikmalaya->id, 'name' => 'CIHIDEUNG'],
            ['regency_id' => $kotatasikmalaya->id, 'name' => 'CIPEDES'],
            ['regency_id' => $kotatasikmalaya->id, 'name' => 'TAWANG'],
            ['regency_id' => $kotatasikmalaya->id, 'name' => 'INDIHIANG'],
            ['regency_id' => $kotatasikmalaya->id, 'name' => 'KAWALU'],
            ['regency_id' => $kotatasikmalaya->id, 'name' => 'CIBEUREUM'],
            ['regency_id' => $kotatasikmalaya->id, 'name' => 'TAMANSARI'],
            ['regency_id' => $kotatasikmalaya->id, 'name' => 'MANGKUBUMI'],
            ['regency_id' => $kotatasikmalaya->id, 'name' => 'BUNGURSARI'],
            ['regency_id' => $kotatasikmalaya->id, 'name' => 'PURBARATU'],
            ['regency_id' => $kotabanjar->id, 'name' => 'BANJAR'],
            ['regency_id' => $kotabanjar->id, 'name' => 'PATARUMAN'],
            ['regency_id' => $kotabanjar->id, 'name' => 'PURWAHARJA'],
            ['regency_id' => $kotabanjar->id, 'name' => 'LANGENSARI'],
        ];
        foreach ($dataVillages as $key => $value) {
            Villages::create($value);
        }
    }
}
